name: Repack thunk
on:
  workflow_call:
    inputs:
      username:
        description: A username passed from the caller workflow
        default: 'john-doe'
        required: false
        type: string

jobs:
  print-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Print username
        run: echo The username is ${{ inputs.username }}
